### ISSUE TITLE
Temperature of AMD CPU displays as NA

### ISSUE THREAD

**Issue by EricAndrechek** [KrispyCamel4u/SysMonTask#22]
I was previously running things in Psensor and can see lots of temperatures there, but SysMonTask is unable to identify a CPU temperature. Is there a way to specify where to get temperature data from or any other fix for this? Thanks!

**Comment by KrispyCamel4u** [comment]
Hi, 
It relies on psutil to get the temps. Can you run the below snippet of code let me know the output.
```
import psutil as ps
print(ps.sensors_temperatures())
```

**Comment by EricAndrechek** [comment]
Sure, thanks for the quick response!
```{'acpitz': [shwtemp(label='', current=16.8, high=20.8, critical=20.8), shwtemp(label='', current=16.8, high=20.8, critical=20.8)], 'nvme': [shwtemp(label='Composite', current=36.85, high=84.85, critical=84.85), shwtemp(label='Sensor 1', current=36.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=44.85, high=65261.85, critical=65261.85)], 'k10temp': [shwtemp(label='Tctl', current=43.375, high=None, critical=None), shwtemp(label='Tdie', current=43.375, high=None, critical=None), shwtemp(label='Tccd1', current=33.75, high=None, critical=None)], 'iwlwifi_1': [shwtemp(label='', current=28.0, high=None, critical=None)], 'amdgpu': [shwtemp(label='edge', current=43.0, high=94.0, critical=94.0)]}```

**Comment by KrispyCamel4u** [comment]
Which CPU and computer you are using?

**Comment by EricAndrechek** [comment]
AMD Ryzen 7 3700x, Gigabyte X570 UD ATX AM4 Motherboard, Ubuntu 20.10

**Comment by KrispyCamel4u** [comment]
Thanks a lot, 
It is because kernel drivers uses a different label in regard to intel and AMD CPUs.  I will fix it soon.

**Comment by EricAndrechek** [comment]
Makes sense. Correct me if I am wrong, but could you not just output like the first temperature item as a fallback?

**Comment by KrispyCamel4u** [comment]
The order in which different hardware temperature appear might not be the same for different systems and also without checking to what hardware does the first list of temperature belongs to, isn't right. In your case, the first entry being the acpitz which isn't the CPU temps, the k10temp is what show the CPU temps for AMD.

**Comment by Seltonu** [comment]
Hello, chiming in to say I have the same issue on a Ryzen 5900x, temperature is listed as "NA"

The output of the above command you listed is as follows:

{'acpitz': [shwtemp(label='', current=16.8, high=20.8, critical=20.8), shwtemp(label='', current=16.8, high=20.8, critical=20.8)], 'nvme': [shwtemp(label='Composite', current=43.85, high=74.85, critical=79.85), shwtemp(label='Composite', current=40.85, high=76.85, critical=78.85), shwtemp(label='Sensor 1', current=40.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=48.85, high=65261.85, critical=65261.85)], 'amdgpu': [shwtemp(label='edge', current=53.0, high=100.0, critical=100.0), shwtemp(label='junction', current=57.0, high=110.0, critical=110.0), shwtemp(label='mem', current=58.0, high=100.0, critical=100.0)], 'k10temp': [shwtemp(label='Tctl', current=52.625, high=None, critical=None), shwtemp(label='Tdie', current=52.625, high=None, critical=None)], 'iwlwifi_1': [shwtemp(label='', current=41.0, high=None, critical=None)]}

**Comment by KrispyCamel4u** [comment]
Hi,
This has been fixed in the latest release. Can you update me about that.

**Comment by EricAndrechek** [comment]
I tried with the 1.1.1 update that you released a couple of days ago still without success. I have since changed my kernel modules for sensors to get more information, so now my sensors output is:
```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +28.0°C  

it8628-isa-0a40
Adapter: ISA adapter
in0:          948.00 mV (min =  +0.00 V, max =  +3.06 V)
in1:            2.03 V  (min =  +0.00 V, max =  +3.06 V)
in2:            2.03 V  (min =  +0.00 V, max =  +3.06 V)
in3:            2.03 V  (min =  +0.00 V, max =  +3.06 V)
in4:            1.12 V  (min =  +0.00 V, max =  +3.06 V)
in5:          900.00 mV (min =  +0.00 V, max =  +3.06 V)
in6:            1.38 V  (min =  +0.00 V, max =  +3.06 V)
3VSB:           3.29 V  (min =  +0.00 V, max =  +6.12 V)
Vbat:           3.07 V  
CPU_FAN:      1108 RPM  (min =   10 RPM)
SYS_FAN1:      544 RPM  (min =    0 RPM)
SYS_FAN2:      604 RPM  (min =    0 RPM)
Chipset fan:  1477 RPM  (min =    0 RPM)
CPU_OPT:         0 RPM  (min =    0 RPM)
SYS1 (rear):   +27.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
SYS2 (front):  +27.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
CPU:           +47.0°C  (low  =  +0.0°C, high = +90.0°C)
PCIe:          +35.0°C  (low  = +127.0°C, high = +127.0°C)
VRM:           +32.0°C  (low  = +127.0°C, high = +127.0°C)
Chipset:       +49.0°C  (low  = -16.0°C, high = +90.0°C)
intrusion0:   ALARM

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +16.8°C  (crit = +20.8°C)
temp2:        +16.8°C  (crit = +20.8°C)

zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:   938.00 mV 
SVI2_SoC:      1.09 V  
Tdie:         +46.4°C  (high = +95.0°C)
Tctl:         +46.4°C  
Tccd1:        +34.0°C  
SVI2_P_Core:   3.09 W  
SVI2_P_SoC:    9.61 W  
SVI2_C_Core:   3.29 A  
SVI2_C_SoC:    8.83 A  

amdgpu-pci-0a00
Adapter: PCI adapter
vddgfx:      950.00 mV 
fan1:         745 RPM  (min =    0 RPM, max = 3500 RPM)
edge:         +44.0°C  (crit = +94.0°C, hyst = -273.1°C)
power1:       39.10 W  (cap = 145.00 W)
```
Zenpower is a kernel module for additional information about AMD processors so that should return Tdie or Tccd1. Alternatively, but less accurately, there is also CPU socket temperature information from the motherboard coming in from the it8628 module.

**Comment by KrispyCamel4u** [comment]
> there is also CPU socket temperature information from the motherboard coming in from the it8628 module.

Thank you, I found where I missed. I will patch it up soon.

**Comment by KrispyCamel4u** [comment]
Hi,
A new version is out and this issue has been fixed and some overall modifications and new features have been added, check out readme to know more.
Please verify and let me know if you still face this issue or not in new release.

**Comment by EricAndrechek** [comment]
Unfortunately, it still doesn't appear to be displaying the temperature. I have confirmed I am on version 1.3.7, and then the `sensors` command is still displaying things with zenpower. 
![sysmontask](https://user-images.githubusercontent.com/35144594/115030602-47643f80-9e95-11eb-8b76-ee5cd7a76d00.png)

**Comment by KrispyCamel4u** [comment]
> Unfortunately, it still doesn't appear to be displaying the temperature. I have confirmed I am on version 1.3.7, and then the `sensors` command is still displaying things with zenpower.
> ![sysmontask](https://user-images.githubusercontent.com/35144594/115030602-47643f80-9e95-11eb-8b76-ee5cd7a76d00.png)

Hi
Thanks for letting me know, I will check once more :(

**Comment by EricAndrechek** [comment]
Let me know if there is something I can do from my end to help out here!

**Comment by KrispyCamel4u** [comment]
> Let me know if there is something I can do from my end to help out here!

Thanks a lot.
Can you run this small code.
```
import psutil as ps
a=ps.sensors_temperatures()
for lis in a['k10temp']:
    print(lis,lis.label)
    if lis.label=='Tdie':
        print("done")
```
and let me know what it gives output.

**Comment by KrispyCamel4u** [comment]
> Ah ok I see what has gone wrong here. So in the original post I made I had mentioned that k10temp was where it should be coming from, but I have since switched things up to use the zenpower module. In my later comment, I posted my updated sensors output, which no longer includes k10temp but instead zenpower. So when running the code provided, it gives a key error since k10temp is not in the list. If I change the code snippet you have provided to:
> 
> ```python
> import psutil as ps
> a=ps.sensors_temperatures()
> for lis in a['zenpower']:
>     print(lis,lis.label)
>     if lis.label=='Tdie':
>         print("done")
> ```
> 
> I get:
> 
> ```
> shwtemp(label='Tdie', current=48.75, high=95.0, critical=95.0) Tdie
> done
> shwtemp(label='Tctl', current=48.75, high=None, critical=None) Tctl
> shwtemp(label='Tccd1', current=52.5, high=None, critical=None) Tccd1
> ```

ok I see, so it depends upon kernel module. 
You can change this like in the source code to get the temps:
line 172,173 in /usr/lib/python3/dist-packages/sysmontask/cpu.py
And it will be fixed.
I will also add the "zenpower" key also in the source but it actually might change with different kernels. But for the time being it is fine. In case if others also has the same issue this can be generalised from their help. 

For any other issue please let me know. And thank you once again.

**Comment by EricAndrechek** [comment]
Fantastic, thank you! I imagine it will be a pain sourcing information from different modules for different motherboards and such, but I do think that yes some simple try catching for different module names would be great.

**Comment by Seltonu** [comment]
Hello! Just wanted to say the new update works great, temperature is now showing for my Ryzen 5000 series! Very very appreciated, and side note the updated UI is wonderful!

![image](https://user-images.githubusercontent.com/10287568/115104924-c21e7080-9f10-11eb-8da0-c756c4dca17e.png)
